//! Persisted compositor-specific session startup choices.
use crate::{
    control::{self, Store},
    discovery,
    model::{Candidate, Kind, Session},
    ownership,
};
use anyhow::{Context, Result, ensure};
use std::{fs, path::Path};

pub fn configure(dir: &Path, compositor: &str, candidate: Option<&Candidate>) -> Result<()> {
    let compositor = compositor.to_lowercase();
    ensure!(
        !compositor.is_empty()
            && compositor
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_'),
        "Use a compositor name such as niri, hyprland or sway"
    );
    let store = Store::open(dir)?;
    let mut state = store.load()?;
    ensure!(
        state.pending.is_none(),
        "Finish recovery or the current trial before changing autostart"
    );
    if let Some(c) = candidate {
        ensure!(
            c.kind == Kind::Shell,
            "Only desktop shells can be autostart choices"
        );
        ensure!(
            c.compositors.is_empty() || c.compositors.contains(&compositor),
            "This shell declares a different compositor requirement"
        );
        state.installed.entry(c.id.clone()).or_insert(c.clone());
        state.autostart.insert(compositor, c.id.clone());
    } else {
        state.autostart.remove(&compositor);
    }
    let target = discovery::config_home().join("autostart/shellswitch-session.desktop");
    let old = fs::read_to_string(&target).unwrap_or_default();
    ensure!(
        old.is_empty() || old.contains("X-Shellswitch-Managed=true"),
        "Autostart entry exists and is not owned by Shellswitch"
    );
    let quote = |p: &Path| -> String {
        format!(
            "\"{}\"",
            p.to_string_lossy()
                .replace('\\', "\\\\")
                .replace('"', "\\\"")
                .replace('%', "%%")
        )
    };
    let text = format!(
        "[Desktop Entry]\nType=Application\nName=Shellswitch session shell\nX-Shellswitch-Managed=true\nExec={} --state-dir {} autostart\n",
        quote(&std::env::current_exe()?),
        quote(dir)
    );
    // Saving this choice does not switch or stop any shell.
    if state.autostart.contains_key("hyprland") {
        install_generated_hypr_hook(dir, &state)?;
    }
    ownership::write(&target, &ownership::text(&text, 0o644))?;
    state.last_event =
        "Saved compositor-specific autostart choices; current desktop unchanged".into();
    store.save(&state)
}

pub fn launch(dir: &Path) -> Result<()> {
    let session = Session::detect();
    let store = Store::open(dir)?;
    let state = store.load()?;
    let Some(id) = state.autostart.get(&session.compositor) else {
        return Ok(());
    };
    ensure!(
        state.pending.is_none(),
        "Recovery or handoff is pending; run shellswitch recover --yes"
    );
    ensure!(
        !state.disabled.contains(id),
        "Autostart shell is emergency-disabled"
    );
    if let Some(active) = &state.active
        && control::healthy(active)
    {
        if let Some(pid) = &active.process {
            ensure!(
                crate::process::same_session(pid.pid),
                "A shell remains active in another session; it will not be stopped"
            );
        }
        if &active.candidate.id == id {
            return Ok(());
        }
    }
    let candidate = state
        .installed
        .get(id)
        .context("Autostart choice is no longer registered")?
        .clone();
    session
        .compatibility(&candidate)
        .map_err(anyhow::Error::msg)?;
    let all: Vec<_> = state.installed.values().cloned().collect();
    drop(store);
    control::switch(dir, &candidate, &session, &all)?;
    control::keep(dir)
}

// This supported generator advertises settings.json as its source of truth.
// Never edit its generated autostart.conf.
fn install_generated_hypr_hook(dir: &Path, state: &control::State) -> Result<()> {
    let root = discovery::config_home().join("hypr");
    let generated = fs::read_to_string(root.join("config/autostart.conf")).unwrap_or_default();
    if !generated.contains("AUTOGENERATED FROM SETTINGS.JSON") {
        return Ok(());
    }
    let path = root.join("settings.json");
    let original = fs::read_to_string(&path)?;
    let mut settings: serde_json::Value = serde_json::from_str(&original)?;
    let Some(startup) = settings
        .get_mut("startup")
        .and_then(serde_json::Value::as_array_mut)
    else {
        return Ok(());
    };
    let quote = |s: &str| format!("'{}'", s.replace('\'', "'\"'\"'"));
    let hook = format!(
        "{} --state-dir {} autostart",
        quote(&std::env::current_exe()?.to_string_lossy()),
        quote(&dir.to_string_lossy())
    );
    let home = std::env::var("HOME").unwrap_or_default();
    let known: Vec<_> = state
        .installed
        .values()
        .filter_map(|c| c.source.canonicalize().ok())
        .collect();
    let mut changed = false;
    for item in startup.iter_mut() {
        let Some(command) = item.get("command").and_then(|v| v.as_str()) else {
            continue;
        };
        let parts: Vec<_> = command.split_whitespace().collect();
        if parts.len() == 3 && ["qs", "quickshell"].contains(&parts[0]) && parts[1] == "-p" {
            let expanded = if let Some(rest) = parts[2].strip_prefix("~/") {
                format!("{home}/{rest}")
            } else {
                parts[2].into()
            };
            if Path::new(&expanded)
                .canonicalize()
                .ok()
                .is_some_and(|p| known.contains(&p))
            {
                item["command"] = serde_json::Value::String(hook.clone());
                changed = true;
            }
        }
    }
    if !changed {
        return Ok(());
    }
    let backup = dir
        .join("startup-backups")
        .join(format!("hypr-settings-{}.json", ownership::nonce()?));
    ownership::write(&backup, &ownership::read(&path)?)?;
    let mode = std::os::unix::fs::PermissionsExt::mode(&fs::metadata(&path)?.permissions());
    ownership::write(
        &path,
        &ownership::text(&serde_json::to_string_pretty(&settings)?, mode),
    )?;
    Ok(())
}
